name: Test con Playwright

on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Instalar dependencias
      run: npm install

    - name: Instalar Playwright
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx cross-env HEADLESS=true BROWSER_TYPE=${{ matrix.browser }} VIDEO=true SCREENSHOT=true cucumber-js Features/*.feature --format=json:output/report.json
   
    - name: Generar reporte  
      run: npm run reporte

    - name: Guardar imagenes
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: ./screenshots

    - name: Guardar Videos
      uses: actions/upload-artifact@v2
      with:
        name: videos
        path: ./videos

    - name: Guardar Reporte
      uses: actions/upload-artifact@v2
      with:
        name: reporte
        path: ./output
