name: Test Regression on-push

on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Instalar dependencias
      run: npm install

    - name: Instalar Playwright
      run: npx playwright install --with-deps

    - name: Crear carpeta "screenshots"
      run: mkdir -p screenshots
      
    - name: Run Playwright tests
      run: npx cross-env HEADLESS=true BROWSER_TYPE=${{ matrix.browser }} VIDEO=true SCREENSHOT=true cucumber-js Features/*.feature --format=json:output/report.json
   
    - name: Generar reporte  
      run: npm run generate-report

    - name: Guardar imagenes
      uses: actions/upload-artifact@v4
      with:
        name: screenshots-${{ matrix.browser }}
        path: ./screenshots

    - name: Guardar Videos
      uses: actions/upload-artifact@v4
      with:
        name: videos-${{ matrix.browser }}
        path: ./videos

    - name: Guardar Reporte html
      uses: actions/upload-artifact@v4
      with:
        name: reportes-${{ matrix.browser }}
        path: ./output
