name: Test Regression on-demand

on:
  workflow_dispatch:
    inputs:
      VIDEO:
        description: '¿Grabar video?'
        required: true
        default: 'true'
        type: choice
        options: 
          - true
          - false
      SCREENSHOT:
        description: '¿Tomar capturas de pantalla?'
        required: true
        default: 'true'
        type: choice
        options: 
          - true
          - false
      BROWSERS:
        description: 'Selecciona el navegador(es) en el que deseas ejecutar las pruebas'
        required: true
        default: 'chromium'
        type: choice
        options: 
          - chromium
          - firefox
          - webkit

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HEADLESS: true
      BROWSER_TYPE: ${{ github.event.inputs.BROWSERS }}
      VIDEO: ${{ github.event.inputs.VIDEO }}
      SCREENSHOT: ${{ github.event.inputs.SCREENSHOT }}
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Instalar dependencias
      run: npm install

    - name: Instalar Playwright
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx cross-env HEADLESS=true BROWSER_TYPE=${{ github.event.inputs.BROWSERS }} VIDEO=${{ github.event.inputs.VIDEO }} SCREENSHOT=${{ github.event.inputs.SCREENSHOT }} cucumber-js Features/*.feature --format=json:output/report.json

    - name: Generar reporte  
      run: npm run generate-report
      
    - name: Guardar imagenes
      if: ${{ github.event.inputs.SCREENSHOT == 'true' }}
      uses: actions/upload-artifact@v2
      with:
        name: screenshots-${{ github.event.inputs.BROWSERS }}
        path: ./screenshots

    - name: Guardar Videos
      if: ${{ github.event.inputs.VIDEO == 'true' }}
      uses: actions/upload-artifact@v2
      with:
        name: videos-${{ github.event.inputs.BROWSERS }}
        path: ./videos

    - name: Guardar Reporte
      uses: actions/upload-artifact@v2
      with:
        name: reporte-${{ github.event.inputs.BROWSERS }}
        path: ./output
